### ISSUE TITLE
Stripping doctype.

### ISSUE THREAD

**Issue by allanhortle** [jgallen23/grunt-inline-css#11]
Like the title says. I have a plain html page and by using `grunt inlinecss` the doctype gets removed. Took me way to long to realise what was happening. Weird rendering issues all over the place.

**Comment by Ethanhackett** [comment]
+1 [duplicate issue](https://github.com/jgallen23/grunt-inline-css/issues/17)

**Comment by knynkwl** [comment]
fixed with : https://github.com/jgannonjr/juice/commit/969c4ab913d4bd1a1f8087aa4307a1b091c724cc

**Comment by blacksun1** [comment]
Tests are in place for this and @knynkwl did say it was fixed so I will close. Please re-open if it is still an issue.
