### ISSUE TITLE
Inline CSS removes doctype declaration

### ISSUE THREAD

**Issue by ghost** [jgallen23/grunt-inline-css#17]
When I inline css the doctype that is present in the source html file is removed in the output. Please can you change this behaviour or provide an option that allows for the retention on the doctype declaration.

**Comment by dotherightthing** [comment]
This is still an issue, I'm post-processing with `grunt-replace` to work around this for now:

    replace: {
      doctype: {
        options: {
          patterns: [
            {
              match: /\n\<html xmlns="http:\/\/www.w3.org\/1999\/xhtml"\>/,
              replacement: '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html xmlns="http://www.w3.org/1999/xhtml">'
            }
          ]
        },
        files: {
          'email_inlined.html': 'email_inlined.html'
        }
      }
    }

**Comment by blacksun1** [comment]
This should be now fixed in master
