### ISSUE TITLE
Not working for <link> tags

### ISSUE THREAD

**Issue by jfurrow** [jgallen23/grunt-inline-css#18]
The task is working for `<style>` definitions, but not for `<link>` referencing external CSS files.

**Comment by djwa** [comment]
Same problem here, "extraCSS" juice option doesn't work either.

**Comment by regepan** [comment]
Did you solve this problem?

**Comment by blacksun1** [comment]
Hi @jfurrow and @regepan,

The main test, `fixtures/in.html` does have an example of a stylesheet working via a `<link>` tag. I'm going to close this for now, please re-open with a broken example if you have one.


Regards,
