### ISSUE TITLE
Target directory / file type instead of file

### ISSUE THREAD

**Issue by whatsnewsaes** [jgallen23/grunt-inline-css#23]
It looks like the only way to get this grunt plugin to work is to manually map the file path. Is there a way to target a directory rather than explicitly defining which files need to be inlined?

Thanks for a great plugin!

`
files: {
                '_output/*.html': '_input/*.html'
         }
`

instead of 
`
files: {
                '_output/index.html': '_input/index.html'
            }
`

**Comment by enstyled** [comment]
I made it work by setting a files array with "expand: true":
```
inlinecss: {
    main: {
        files: [
            {
                expand: true,
                src: '*.html',
                dest: './'
            }
        ]
    }
}
```
Reference: http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically

**Comment by whatsnewsaes** [comment]
Thanks!
