### ISSUE TITLE
looking for help on this project

### ISSUE THREAD

**Issue by jgallen23** [jgallen23/grunt-inline-css#26]
As you can probably tell, I've neglected this repo. I'm looking for somebody to help me update this repo. Anybody interested in helping me out?

**Comment by designil** [comment]
Hello, I would love to help. I'm going to make use of this too.

**Comment by jgallen23** [comment]
@designil awesome! I'll make you a contributor

**Comment by blacksun1** [comment]
Hey, is this still be worked on? I'd also like to help as it looks like the project has died off a bit again.

**Comment by jgallen23** [comment]
@blacksun1 added you as a collaborator

**Comment by blacksun1** [comment]
Hey @jgallen23, want to give me access to npm as well?

**Comment by jgallen23** [comment]
@blacksun1 whats your npm name?

**Comment by blacksun1** [comment]
[blacksun1](https://www.npmjs.com/~blacksun1)

**Comment by jgallen23** [comment]
done
