### ISSUE TITLE
Is there a way to process a whole folder of files, without explicitly stating each one?

### ISSUE THREAD

**Issue by digitaloutback** [jgallen23/grunt-inline-css#35]
Ideally, we would be able to set a directory of files for GIC to parse and specify a target directory to dump them.

Is this possible?

**Comment by royscheepens** [comment]
Very interested in this feature also.

**Comment by mohamnag** [comment]
not sure if this is what you want but technically you can do it on any grunt task by rewriting files part as follows:
```
files: [{
          expand: true,
          cwd: '<%= source %>',
          src: '**/*.{htm,html}',
          dest: '<%= dest %>'
        }]
```

**Comment by abusedmedia** [comment]
Works without [] like:

```js
files: {
          expand: true,
          cwd: '<%= source %>',
          src: '**/*.{htm,html}',
          dest: '<%= dest %>'
}
```

**Comment by blacksun1** [comment]
HI,

Anyone want to update the README with this fact?


Regards,

**Comment by mohamnag** [comment]
this actually belongs to the README of grunt and not each single grunt plugin.

**Comment by blacksun1** [comment]
Yes, true. I'll leave this link here in case anyone needs it next time

http://gruntjs.com/configuring-tasks#files


Regards,
