### ISSUE TITLE
inliner is turning jpegs into base64

### ISSUE THREAD

**Issue by DarthOstrich** [jgallen23/grunt-inline-css#37]
Hi, everytime i use the inline css using grunt it keeps converting some of the images into base64. Any idea why, or how I can stop this from happening?

**Comment by stevepiron** [comment]
+1, this is also an issue for me.

**Comment by DarthOstrich** [comment]
hey steve, i dont think this git is monitored any more, i switched over to premailer. check that out, its pretty cool. https://github.com/premailer/premailer

**Comment by Naemy** [comment]
Thanks @stevepiron, that was useful :)

**Comment by blacksun1** [comment]
Hi @DarthOstrich,

If you are still interested in using this tool, I would love to get some idea of the actual code that was failing for you.

**Comment by blacksun1** [comment]
Actually, please see #34 which describes a fix for this issue.
