### ISSUE TITLE
src html file in subdir breaks css fetching

### ISSUE THREAD

**Issue by publicJorn** [jgallen23/grunt-inline-css#5]
Hi,
It seems that the root of the project (where the Gruntfile is) is always used as root for the href in the <link/> tags:

**structure**
root/
root/src
root/src/index.html (has link href="css/style.css")
root/src/css/style.css

grunt-inline-css parses the link href and searches for: root/css/style.css

**init**
this happens both with static and dynamic files array:

`files: [{'build/index.html': 'src/index.html'}]`

OR

```
files: [{
  expand: true,
  cwd: 'src/',
  src: '*.html',
  dest: 'build'
}]
```

Is it possible for you to set the html file as "root" for parsing the link href?

**Comment by mohamnag** [comment]
it seems it depends on how the style file is linked. I have this structure:
dist/
dist/subdir1/file.html
dist/css/file.css

in my file.html

**Comment by mohamnag** [comment]
forget about it, I could solve it by setting this on options
```
          webResources: {
            relativeTo: 'dist/'
          }
```

**Comment by computersarecool** [comment]
Thanks for pointing this out @mohamnag I too think this should go in the README

**Comment by woraperth** [comment]
@mohamnag @computersarecool Do you mind submitting the pull request for that ? I would be happy to help :)

**Comment by uixmat** [comment]
In your HTML files the stylesheet `href` **must be a relative path**.
```html
<link rel="stylesheet" type="text/css" href="../css/styles.css">
```
