### ISSUE TITLE
Does not install using Node.js Tools for Visual Studio

### ISSUE THREAD

**Issue by custa1200** [jgallen23/grunt-inline-css#9]
As the title suggests when using the NPM manager the grunt-inline-css package fails to install.Below is the console block that seems to show the error.

npm http 200 https://registry.npmjs.org/domhandler/-/domhandler-2.2.0.tgz
npm ERR! contextify@0.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.6 install script.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "update" "grunt-inline-css" "--save"
npm ERR! cwd D:\Projects\ModernMail\ModernMail
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm http GET https://registry.npmjs.org/core-util-is

**Comment by albanx** [comment]
I have the same issue actually, but it has to be posted here, because probably it is not working even for you.
